### ISSUE TITLE
EPERM on mkdir

### ISSUE THREAD

**Issue by limitusus** [tagomoris/fluent-plugin-file-alternative#17]
In #16 file-alternative does `chmod` for the directory newly created.
It caused an error in my environment with this version, where the parent directory's owner is not same as fluentd and is set setgid bit.

The error stacktrace follows.
I think there would be better to have an option "not invoke chmod".
```
2015-07-23 19:13:30 +0900 [error]: failed to write data: path /data/accesslog/XXXX/log_for_host.20150723
2015-07-23 19:13:30 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-23 19:46:32 +0900 error_class="Errno::EPERM" error="Operation not permitted @ chmod_internal - /data/accesslog" plugin_id="object:10bc36c"
2015-07-23 19:13:30 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/fileutils.rb:1348:in `chmod'
2015-07-23 19:13:30 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/fileutils.rb:1348:in `chmod'2015-07-23 19:13:30.296435500   2015-07-23 19:13:30 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/fileutils.rb:996:in `block in chmod'
2015-07-23 19:13:30 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/fileutils.rb:995:in `each'
2015-07-23 19:13:30 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/fileutils.rb:995:in `chmod'2015-07-23 19:13:30.296452500   2015-07-23 19:13:30 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-file-alternative-0.2.0/lib/fluent/plugin/out_file_alternative.rb:142:in `block in write'
```

**Comment by tagomoris** [comment]
Patches welcome :D
